### ISSUE TITLE
Step 6. "6504 segmentation fault"

### ISSUE THREAD

**Issue by nailabc** [McMahonLab/16STaxAss#100]
Hi, I'm following the workflow and I couldn't run the step 6. Could anybody help me?
I get the following message:
$ RScript plot_blast_hit_stats.R otus.custom.blast.table.modified 98 plots
/Users/Naila/R /Users/Naila/anaconda/lib/R/library
 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 7: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
 8: loadNamespace(package, lib.loc)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
13: try({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)})
14: library(package = "reshape", logical.return = TRUE, lib.loc = library.path)
15: get.necessary.packages()
An irrecoverable exception occurred. R is aborting now ...
[1]    6504 segmentation fault  RScript plot_blast_hit_stats.R otus.custom.blast.table.modified 98 plots

**Comment by rrohwer** [comment]
Hi Naila,

That's the only R script that loads a package. It's supposed to install and then remove it if you don't already have it so that you don't have to do the extra step, but maybe that is the problem. 

1. Can you tell me what type of computer/operating system you're using?

2. Try troubleshooting by opening up the R console and typing:
```
install.packages("reshape")
```
and then try running that script again.

3. That step is a check, so you can skip it and continue the workflow and you won't be missing any intermediate files. (But I still think it's important to check the BLAST settings at some point.)

Please let me know how it goes so I can fix this mistake for others too.

Thanks!

Robin

**Comment by nailabc** [comment]
Hi, Robin
Sorry I forgot to tell that I'm using a MacOS (version 10.12.6). And I in fact tried to install the reshape package directly on R but the problem keeps happening (it always return this "segmentation fault"). I could continue the workflow but I agree with you that it's important to check the BLAST, ideally I wouldn't like to skip this step (or at least I'll try to come back and fix it later). Hopefully you can help me to figure this out!

**Comment by rrohwer** [comment]
hmmm...  can you send me the results of 
```
head -200 otus.custom.blast.table.modified > fixbug.txt
```
and e-mail fixbug.txt to me so I can start by double-checking the formatting on my computer? my e-mail is rrohwer@wisc.edu

**Comment by joshamilton** [comment]
@nailabc The segmentation fault may arise from packages which were compiled using a previous version of R and/or R packages being installed in multiple locations. Some possible solutions are described [here](https://github.com/hadley/devtools/issues/1292).

**Comment by rrohwer** [comment]
Thanks Josh!  Naila, check out the comment on Josh's link by "merliseclyde". My OS is still 10.10 and you are using 10.12, so that could explain why I have not had an issue on my computer.

**Comment by nailabc** [comment]
Thanks you two! I did what it's described in the link (moved libraries in the user library ~/user/Library/R/version# to other location). In fact I have R packages installed in multiple locations (both in the user library and in the system library, like explaining here: http://shiny.rstudio.com/articles/upgrade-R.html).
However, I had another bug while running the Rscript on step #13. I'll report it as a new issue.
