### ISSUE TITLE
step 13. Error in apply(X = tax.nums, MARGIN = 2, FUN = as.numeric) : dim(X) must have a positive length

### ISSUE THREAD

**Issue by nailabc** [McMahonLab/16STaxAss#101]
I'm running the steps of the workflow in a MacOS 10.12.6 and I couldn't figure out how to solve the following error while trying the step 13:
$ Rscript find_classification_disagreements.R otus.98.taxonomy otus.general.taxonomy ids.above.98 conflicts_98 98 85 70

comparing seqIDs the workflow classified with custom database to how general database would have classified them.

Error in apply(X = tax.nums, MARGIN = 2, FUN = as.numeric) :
  dim(X) must have a positive length
Calls: do.bootstrap.cutoff -> apply
Execution halted

**Comment by rrohwer** [comment]
Hi Naila,

Can you show me the beginning of those input files? My guess is that something is misformatted and that led to a step in the processing having an empty vector.  So show me the results of:
```
head otus.98.taxonomy
head otus.general.taxonomy
head ids.above.98
```

Thanks,
Robin

**Comment by nailabc** [comment]
$ head otus.98.taxonomy
seq18998;size=17;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(58);betI(58);betI-A(58);Lhab-A4(45);
seq45268;size=2;k__Bacteria(100);p__Bacteroidetes(100);unclassified(100);unclassified(100);unclassified(100);unclassified(100);unclassified(100);
seq68164;size=3;k__Bacteria(100);p__Bacteroidetes(100);c__Flavobacteriia(100);o__Flavobacteriales(100);bacV(100);unclassified(100);unclassified(100);

$ head otus.general.taxonomy
seq64;size=60978;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(100);f__Oxalobacteraceae(100);g__Polynucleobacter(100);s__(100);
seq28;size=56747;k__Bacteria(100);p__Actinobacteria(100);c__Actinobacteria(100);o__Actinomycetales(100);f__ACK-M1(100);g__(100);s__(100);
seq25;size=54846;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(100);f__Oxalobacteraceae(100);g__(100);s__(100);

$ head ids.above.98
seq64;size=60978
seq28;size=56747
seq25;size=54846
seq3;size=40997
seq108;size=32457

**Comment by rrohwer** [comment]
Hi Naila,

The issue is the `size=` column. It looks like that might be part of your sequence names since it is also in the list of sample ID's. You'll need to re-name your sequences to not contain any semicolons. For example, you could use a grep or sed command that only removes the first instance on a line. I'll make a note to add this formatting requirement into the formatting guidelines at the beginning. 

Thanks!!

Robin

**Comment by nailabc** [comment]
Thanks, Robin! In fact I forgot to remove the ;size=* information. Now I did it and I was able to run the script BUT I get a warning message like this:

WARNING!! The Indexing of your files is messed up!!
You have to fix this or all your results will be wrong!
(somehow the seqID order is not the same in both, even though the reformatting functions in this script are supposed to do that.)

I don't understand why because I followed all the steps with no problem (but maybe I missed something in the way...)

Here is the head of the files now in case it helps you to help me :)

$ head otus.98.taxonomy otus.general.taxonomy ids.above.98
==> otus.98.taxonomy <==
seq452146;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Methylophilales(100);betIV(100);betIV-A(88);unclassified(87);
seq2475321;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(100);betVII(66);betVII-B(64);betVII-B1(64);
seq564762;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(100);betIII(100);betIII-A(100);betIII-A1(94);
seq173822;k__Bacteria(100);p__Bacteroidetes(100);c__Sphingobacteriia(100);o__Sphingobacteriales(100);bacVI(100);bacVI-B(99);Pedo(99);
seq2881166;k__Bacteria(100);p__Proteobacteria(100);c__Alphaproteobacteria(100);o__Sphingomonadales(100);alfIII(99);unclassified(99);unclassified(99);
seq535197;k__Bacteria(100);p__Proteobacteria(100);c__Alphaproteobacteria(100);o__Rhizobiales(100);unclassified(100);unclassified(100);unclassified(100);
seq1734814;k__Bacteria(100);p__Proteobacteria(100);c__Alphaproteobacteria(100);o__Rhodobacterales(100);alfVI(100);unclassified(100);unclassified(100);
seq65554;k__Bacteria(100);p__Proteobacteria(100);c__Alphaproteobacteria(100);o__Sphingomonadales(100);alfIII(99);unclassified(99);unclassified(99);
seq1858640;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(97);betI(97);betI-A(83);Lhab-A4(65);
seq250412;k__Bacteria(100);p__Bacteroidetes(100);c__[Saprospirae](100);o__[Saprospirales](100);bacI(100);unclassified(100);unclassified(100);

==> otus.general.taxonomy <==
seq6460978;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(100);f__Oxalobacteraceae(100);g__Polynucleobacter(100);s__(100);
seq2856747;k__Bacteria(100);p__Actinobacteria(100);c__Actinobacteria(100);o__Actinomycetales(100);f__ACK-M1(100);g__(100);s__(100);
seq2554846;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(97);f__Oxalobacteraceae(97);g__(95);s__(95);
seq340997;k__Bacteria(100);p__Proteobacteria(100);c__Alphaproteobacteria(100);o__Sphingomonadales(99);f__Sphingomonadaceae(98);g__(95);s__(95);
seq2039679;k__Bacteria(100);p__Verrucomicrobia(100);c__Verrucomicrobiae(100);o__Verrucomicrobiales(100);f__Verrucomicrobiaceae(100);g__(100);s__(100);
seq4537868;k__Bacteria(100);p__Proteobacteria(100);c__Gammaproteobacteria(100);o__Pseudomonadales(100);f__Pseudomonadaceae(100);g__(29);s__(29);
seq237082;k__Bacteria(100);p__Bacteroidetes(100);c__[Saprospirae](100);o__[Saprospirales](100);f__Saprospiraceae(100);g__(91);s__(91);
seq10832457;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(100);f__Comamonadaceae(100);g__Limnohabitans(50);s__(49);
seq1024830;k__Bacteria(100);p__Proteobacteria(100);c__Betaproteobacteria(100);o__Burkholderiales(100);f__Oxalobacteraceae(99);g__(60);s__(60);
seq17019580;k__Bacteria(100);p__Actinobacteria(100);c__Actinobacteria(100);o__Actinomycetales(100);f__ACK-M1(100);g__(100);s__(100);

==> ids.above.98 <==
seq6460978
seq2856747
seq2554846
seq340997
seq10832457
seq1024830
seq17019580
seq6216903
seq2614620
seq1612305

**Comment by rrohwer** [comment]
Hi Naila,

That means that somehow the seqIDs are not the same in all your files. To trouble shoot, I would start by checking `$ wc -l` just to make sure that there are the same number of lines in all your files (an easy check). If that's not the problem, is it at all possible that when you changed your seqID's to remove size= something else was changed by the text parsing too? Which script are you at when you got this message? This warning will show up potentially in multiple steps.

Thanks,

Robin

**Comment by nailabc** [comment]
This appears in the script of the step 13: Rscript find_classification_disagreements.R otus.98.taxonomy otus.general.taxonomy ids.above.98 conflicts_98 98 85 70
I removed the ;size= with this command sed ’s/;size=*//' <otus.fasta >otus2.fasta
it shouldn't change more than the size info, right? And it was important to remove because in the otus.abund file the seqID doesn't contain the size info. 
Just correct me if I'm making any confusion: I should have seqIDs with the same name for the otus.fasta and otus.abund, right?
It also should match the seqIDs within general.fasta and general.taxonomy and within custom.fasta and custom.taxonomy. But probably the problem is in "otus.fasta and otus.abund" since these are not originated from any curated database.

**Comment by nailabc** [comment]
Ok, I just figure out that I took out the ";size=" from the seqID but not the number right after, and then it was added to the SeqID... I'll do it manually to avoid this kind of mistake...

**Comment by rrohwer** [comment]
OK great, let me know if that works. Your understanding in message above is all correct.

**Comment by marschmi** [comment]
I got the same error (and found an easy fix below). I'm using the most recent mothur v.1.43.0 last updated on 04/09/2020. The workflow (note: I'm skipping steps 11-14) seems to run ok until step 15 when I get the following error: 

```
Error in apply(X = tax.nums, MARGIN = 2, FUN = as.numeric) : 
  dim(X) must have a positive length
Calls: do.bootstrap.cutoff -> apply
Execution halted
``` 

This issue seems to be related to the new output format from the updated mothur and is likely related to #111, but instead of the fasta file, it's the taxonomy file. I notice that when I `head` my files, it looks different from @nailabc: instead of a `;` separating the otu name there's a `\t`.

```
$ head -n 4 otus.98.taxonomy 
otu_207	Bacteria(100);Proteobacteria(100);Gammaproteobacteria(100);Betaproteobacteriales(100);betVII(100);betVII-A(100);betVII-A1(100);
otu_214	Bacteria(100);Actinobacteria(100);Acidimicrobiia(100);Microtrichales(100);acIV(100);acIV-B(98);unclassified(98);
otu_223	Bacteria(100);Bacteroidetes(100);Bacteroidia(100);Flavobacteriales(100);bacV(100);unclassified(100);unclassified(100);
otu_225	Bacteria(100);Bacteroidetes(100);Bacteroidia(100);Flavobacteriales(100);bacV(100);unclassifie`d(100);unclassified(100);
```

So then I decided to replace the `\t` with `;` using `sed` & it fixed the issue. 
```
sed $'s/\t/;/g' otus.98.taxonomy > fixed.otus.98.taxonomy
```

Now, I get: 
```
$ head -n 4 fixed.otus.98.taxonomy 
otu_207;Bacteria(100);Proteobacteria(100);Gammaproteobacteria(100);Betaproteobacteriales(100);betVII(100);betVII-A(100);betVII-A1(100);
otu_214;Bacteria(100);Actinobacteria(100);Acidimicrobiia(100);Microtrichales(100);acIV(100);acIV-B(98);unclassified(98);
otu_223;Bacteria(100);Bacteroidetes(100);Bacteroidia(100);Flavobacteriales(100);bacV(100);unclassified(100);unclassified(100);
otu_225;Bacteria(100);Bacteroidetes(100);Bacteroidia(100);Flavobacteriales(100);bacV(100);unclassified(100);unclassified(100);
```

And I'm able to successfully run `find_classification_disagreements.R` in step 15! :)
