### ISSUE TITLE
RunSteps_quickie.sh causes an error if no ids are missing in the BLAST output

### ISSUE THREAD

**Issue by ilnamkang** [McMahonLab/16STaxAss#118]
Thanks for a great resource.

It seems that RunSteps_quickie.sh causes an error at step 7 if no ids are missing in the BLAST output.

Below is the error message I've encountered when I ran RunSteps_quickie.sh using a fasta file containing 260 (=16+244) sequences.

\-----
Added 16 sequences matching the custom database with >=  98 % sequence identity to ids.above.98
Assign taxonomy to these sequences using the Small Custom database

Added 244 sequences matching the custom database with <  98 % sequence identity to ids.below.98
Assign taxonomy to these sequences using the Large General database

cat: ids.missing: No such file or directory
\-----

Just FYI, my workaround below seems to work.
\-----
\# 7
python find_seqIDs_blast_removed.py ${otus}.fasta ${otus}.${custom}.blast.table.modified ids.missing &&
FILE="./ids.missing"
if [ -e $FILE ]; then
	cat ids.below.${pident[0]} ids.missing > ids.below.${pident[0]}.all
else
	cat ids.below.${pident[0]} > ids.below.${pident[0]}.all
fi &&
\-----

Thanks.

**Comment by rrohwer** [comment]
Hi Ilnam,

Thank you so much for reporting this bug! It looks like you solved the problem perfectly, and I'll work on incorporating your solution into the repo during the next week. I'll close the issue once I push your fix. Let me know if you need any specific help in the meantime.

Thanks again,

Robin
