### ISSUE TITLE
Convert workflow to markdown

### ISSUE THREAD

**Issue by joshamilton** [McMahonLab/16STaxAss#14]

**Comment by joshamilton** [comment]
I will convert the workflow to Markdown as I work my way through it.

**Comment by rrohwer** [comment]
@joshamilton I'm starting to think that the README should maybe be a much shorter files with just the setup, defaults and sourcing the bash script.  And putting the detailed descriptions somewhere else- thoughts?

**Comment by joshamilton** [comment]
@rrohwer Yes, that is the model we chose to adopt for the OMD-TOIL project. The 'scripts' folder would contain a README with the detailed descriptions.

**Comment by rrohwer** [comment]
josh might even change to rmd for the floating TOC. <--poem
