### ISSUE TITLE
Create 'dummy' file structure

### ISSUE THREAD

**Issue by joshamilton** [McMahonLab/16STaxAss#26]
Pancho suggested to create empty "placeholder" files to represent files that should be in the user's working directory but aren't in the repo, such as the GG taxonomy files, otus.fasta, etc

**Comment by rrohwer** [comment]
@joshamilton @fmoyaflores I'm not totally sure what this means.  As it is now, step 0. specifies the formatting and naming of files in the working directory.  Do you think I need to be more clear than that?  Asking because it's likely changed since this issue was created.  Thanks!!

**Comment by joshamilton** [comment]
@rrohwer The original idea was to include "empty" files in the repo, which would represent data files the user is expected to have available, such as gg_13_5.taxonomy or otus.fasta. The user would replace the "empty files" with the proper versions prior to running the scripts. If you look at the README, the 'Repo Structure' section shows some of these files. This step needs to be done prior to releasing the software.

**Comment by rrohwer** [comment]
I just think that's confusing and it's better to just list the files needed
instead of having to replace them.

On Sat, Jan 16, 2016 at 7:09 PM, Joshua J Hamilton <notifications@github.com

**Comment by joshamilton** [comment]
Okay, I'll close the issue.
