### ISSUE TITLE
Step 5: Check for 'reshape' Package

### ISSUE THREAD

**Issue by joshamilton** [McMahonLab/16STaxAss#30]
Script plot_blast_hit_stats.R requires use of the 'reshape' package. Need to figure out how to correctly check for this package and install it. Currently the script will fail if 'reshape' is uninstalled. Per this [StackOverflow thread](http://stackoverflow.com/questions/27673000/rscript-there-is-no-package-called), Rscript and Rstudio look for libraries in different places, which is why the script runs when fine via RStudio but not when called via RScript. Maybe just add to the README that users need to have "reshape" installed prior to running the script?

**Comment by joshamilton** [comment]
@cherren8 You're an R expert, can you take a look at this for us? Also check out the discussion on this [pull request](https://github.com/McMahonLab/16STaxAss/pull/29).

**Comment by cherren8** [comment]
I would have done exactly what Alex proposed, since I always use RStudio. I think it's fair to include in the README what packages are required!

**Comment by rrohwer** [comment]
Rscript recognizes neither the default CRAN mirror location nor the default library path.  All you have to do is specify those two things:

```
mirror.location <- "https://cran.mtu.edu" # I just chose an arbitrary one. ppl far away might go slower once?
library.path <- cat(.libPaths()) # this is the default installation path

get.necessary.packages <- function(){
  if (library(package = "reshape", logical.return = TRUE, lib.loc = library.path) == FALSE){
    install.packages("reshape", repos = mirror.location)
    library("reshape", lib.loc = library.path)
  }else{
    library("reshape", lib.loc = library.path)
  }
}
get.necessary.packages()`
```
