### ISSUE TITLE
step 5: add description of generated plots

### ISSUE THREAD

**Issue by rrohwer** [McMahonLab/16STaxAss#50]
1. Choose which plots to actually generate (not ALLL of the current ones!)
2. Include a description of what they are, how to interpret them, what to check for 
   - put this in the workflow, like the file descriptions

**Comment by joshamilton** [comment]
I think the plots `BLAST_hits_used_for_pident_98` and `BLAST_hits_used_for_pidents_90-100` should be included. How is the plot `BLAST_hits_used_overall` useful?

**Comment by rrohwer** [comment]
It's not, I agree.  Except to show you the bottom limit of what BLAST
reports.  which isn't very useful to know.  Of note, and I haven't decided
if it's important b/c it doesn't take that long, is that the 90-100 gets
regenerated multiple times.

On Mon, Jan 18, 2016 at 1:13 PM, Joshua J Hamilton <notifications@github.com
