### ISSUE TITLE
step 2: what is the speed impact of `max_target_seqs`

### ISSUE THREAD

**Issue by rrohwer** [McMahonLab/16STaxAss#52]
We changed `max_target_seqs` to be 5 for checking that blast doesn't leave out good long matches for higher scoring short matches.  This makes the BLAST run take longer. 
- how much longer does it take- is 5 a good number or is 3 sufficient? check with 10 to make sure?

**Comment by joshamilton** [comment]
In my experience the 1st BLAST gives the best full-length pident in over 95% of the cases. We should test on a variety of different data-sets, though.

**Comment by joshamilton** [comment]
Did some further testing on a couple of datasets.

For the iTags from the Mendota MGs (5721 OTUs), BLAST takes 17 seconds for `max_target_seqs = 1` and 20 seconds for `max_target_seqs = 10.` 

For the set of all 16S sequences from one sample (27226 sequences), BLAST takes 7 minutes, 46 seconds for `max_target_seqs = 1` and 8 minutes, 2 seconds for `max_target_seqs = 10.` 

So based on these datasets, the speed impact of `max_target_seqs` is not much.

**Comment by rrohwer** [comment]
Thanks @joshamilton !  Now we have to decide which cutoff to use.  Did you ever see hits lower than 5 being chosen?
