### ISSUE TITLE
step 0: specify formatting changes for SILVA database

### ISSUE THREAD

**Issue by rrohwer** [McMahonLab/16STaxAss#55]
The same way I did for green genes, specify the changes if SILVA isn't compatible.
Even if ours ends up not working with SILVA, should ahve this if we want people to use with other custom databases.

**Comment by joshamilton** [comment]
Created a new branch `silva` which contains scripts for downloading and processing the SILVA database. I wrote variants for the [SILVA Ref NR database](https://www.arb-silva.de/projects/ssu-ref-nr/), and the [version of the NR database](http://blog.mothur.org/2015/12/03/SILVA-v123-reference-files/) modified by Pat Schloss. Don't have a recommendation yet as to which version people should use. 

Trina is aware of the phylogeny conflicts between SILVA and GreenGenes and we are working on a version of the FWDB consistent with SILVA's nomenclature.

**Comment by joshamilton** [comment]
Will add this feature. Which SILVA database should we use? What is the status of the SILVA-compliant FreshTrain?

**Comment by rrohwer** [comment]
The status is: Last time I tried, SILVA had updated but mother & qiime had
not updated their versions. Silva doesn't have a use-able form available
for direct download b/c of stupid choices w/ their delimiters, and so I
gave up for the time being instead of dealing with ARB. Mothur and qiime
have now caught up with the most recent release, easiest is prob. to just
use the mothur NR99 version (ie not seed). To make "compliant" use
the arb-scripts folder to find upper-level name changes btwn SILVA and GG.
Probably won't be much difference there. I won't have time to deal with
until after the bazillion extractions are submitted on Dec 1, so if you can
do that'd be awesome!!!!!!!!

On Sun, Nov 5, 2017 at 7:33 PM, Joshua J. Hamilton <notifications@github.com

**Comment by rrohwer** [comment]
Made silva work. made FreshTrain versions compatible with upper-level silva nomenclature. details and zipped database versions available in the FreshTrain-files folder.
