### ISSUE TITLE
Remove all the dates

### ISSUE THREAD

**Issue by sstevens2** [McMahonLab/16STaxAss#6]
Can I suggest that you remove the dates from the names of files?  I can update this if it is approved of.
Let me know what you think.

**Comment by rrohwer** [comment]
Hi Sarah,

We literally just uploaded them from my file.  Please don't change the file names. I already know what they need to be changed to to match the workflow.

Thanks!

Robin

**Comment by sstevens2** [comment]
Ok.  Looking forward to it then.

**Comment by rrohwer** [comment]
:D

**Comment by sstevens2** [comment]
P.S. Super proud of you, @rrohwer , for getting this up on github!  Awesome start!
