### ISSUE TITLE
an idea for another way to choose good pident

### ISSUE THREAD

**Issue by rrohwer** [McMahonLab/16STaxAss#8]
set to 94% full-length pident and 70% bootstrap cutoff, the single phylum mismatch looks like this:

|  | gg | fw |
| --- | --- | --- |
| seqID | 22992 | 22992 |
| kingdom | k__Bacteria(100) | k__Bacteria(100) |
| phylum | p__Verrucomicrobia(78) | p__Proteobacteria(70) |
| class | c__Verrucomicrobiae(78) | c__Alphaproteobacitera(23) |
| order | o__Verrucomicrobiales(78) | o__Rhizobiales(23) |
| family | f__Verrucomicrobiaceae(78) | alfVII(23) |
| genus | g__Luteolibacter(51) | unclassified |
| species | s__(51) | unclassified |
1. getting only 70% classification by our database seems really low (so maybe 94% is too low).
2. But also I realized that maybe another way to choose a good pident cutoff would be to look for the average bootstrap values at the lineage/clade level.  We only want to compare very similar sequences, so is it fair to say yeah, all the sequences classified in fw should be classified well, to a low level, so pident can be chosen accordingly.  Or is that too recursive.  choose pident too choose what to classify, then classify to choose pident?
3. ALSO I realized that the comparison R script right now compares everything, so gg classifications are compared to gg classification in the workflow.  This means that with a low bootstrap cutoff value you could get mismatches due to stochastic differences, so important to pay attention to the cutoff.

**Comment by rrohwer** [comment]
oops.  the formatting tabs in the table were stripped.  how am I supposed to post that?

**Comment by joshamilton** [comment]
GitHub comments support markdown formatting! Check out the [tutorial](https://guides.github.com/features/mastering-markdown/)!

**Comment by rrohwer** [comment]
1. yes
2. no wrong. will get low clustering p-values when sequences match multiple things well or poorly, as long as they similarly match multiple things.  **so I don't think this is a good idea anymore.**
3. fixed that and it's faster
